[swgp-go]
src.git = "https://github.com/database64128/swgp-go"
src.branch = "main"
fetch.github = "database64128/swgp-go"

[ab-av1]
src.git = "https://github.com/alexheretic/ab-av1"
fetch.github = "alexheretic/ab-av1"

[koboldcpp]
src.git = "https://github.com/LostRuins/koboldcpp"
fetch.github = "LostRuins/koboldcpp"
git.fetchSubmodules = true

[av1an]
src.git = "https://github.com/master-of-zen/av1an"
fetch.github = "master-of-zen/av1an"

[candy]
src.git = "https://github.com/lanthora/candy"
fetch.github = "lanthora/candy"
#[wechat-uos]
#src.webpage = "https://aur.archlinux.org/rpc/?v=5&type=info&arg[]=wechat-uos"
#src.regex = "\"Version\":\"([^\"]+)\""
#src.from_pattern = "(.+):(.+)-(.+)"
#src.to_pattern = "\\2"
#fetch.url = "https://home-store-packages.uniontech.com/appstore/pool/appstore/c/com.tencent.weixin/com.tencent.weixin_$ver_amd64.deb"
