# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  ab-av1 = {
    pname = "ab-av1";
    version = "e65965f74725a1f6d081c583af91af81f68a2268";
    src = fetchFromGitHub {
      owner = "alexheretic";
      repo = "ab-av1";
      rev = "e65965f74725a1f6d081c583af91af81f68a2268";
      fetchSubmodules = false;
      sha256 = "sha256-fUVeeRgfDEggSx1Zpqlneu3W+afR8+6fAnD0F2QQ5uI=";
    };
    date = "2024-03-09";
  };
  av1an = {
    pname = "av1an";
    version = "6632b470640cccc0ade641b87a456d6e127bb4ca";
    src = fetchFromGitHub {
      owner = "master-of-zen";
      repo = "av1an";
      rev = "6632b470640cccc0ade641b87a456d6e127bb4ca";
      fetchSubmodules = false;
      sha256 = "sha256-fZWgN3HOZXsRLCFcLkeRcHNj3fOiTosiC91jAK5xm30=";
    };
    date = "2024-03-27";
  };
  koboldcpp = {
    pname = "koboldcpp";
    version = "f3b7651102c3ce3e4f331b93137dc32d752eada0";
    src = fetchFromGitHub {
      owner = "LostRuins";
      repo = "koboldcpp";
      rev = "f3b7651102c3ce3e4f331b93137dc32d752eada0";
      fetchSubmodules = true;
      sha256 = "sha256-l6XWbstBAl5BQrwrQxLuPX5uKp02hED6vGQQVhZAO9U=";
    };
    date = "2024-03-14";
  };
  swgp-go = {
    pname = "swgp-go";
    version = "ff0d7b3552d6b6c1651791f5fab2de5075746e36";
    src = fetchFromGitHub {
      owner = "database64128";
      repo = "swgp-go";
      rev = "ff0d7b3552d6b6c1651791f5fab2de5075746e36";
      fetchSubmodules = false;
      sha256 = "sha256-oSkIBOC71jgWJEMpv7q0Rd11KRIGxbpYOG2gK8OMLRk=";
    };
    date = "2024-03-12";
  };
}
